### ISSUE TITLE
links to section variables

### ISSUE THREAD

**Issue by affeldt-aist** [affeldt-aist/coq2html#11]
serious: links to section variables can be broken, for instance https://yoshihiro503.github.io/coq2html/mathcomp.analysis.measure.html#classes.G
@proux01

**Comment by yoshihiro503** [comment]
This is due to coqc.

The glob file for the `Context` command is incorrect. The path of the variable is incorrect in the glob file when using the `Context` command. This causes the same problem with `coqdoc`.

The following simple coq code `Hoge.v` will show us the glob file error.

```coq=
Section Sec.
Context (foo : nat).
Definition f := foo.
End Sec.
```

We got the following `Hoge.glob`: 
```glob=
DIGEST f2eaf1911fb0a5cbba737f02a91995ae
FHoge
sec 8:10 <> Sec
R28:30 Coq.Init.Datatypes <> nat ind
binder 22:24 <> foo:1
def 45:45 <> f
R50:52 Hoge <> Sec.foo var
R59:61 Hoge Sec <> sec
```

## My Environment
* Coq version 8.18.0
* OCaml version 4.14.1
* Ubuntu 22.04.2 LTS

**Comment by yoshihiro503** [comment]
I posted the issue on `coq/coq` : https://github.com/coq/coq/issues/18516

**Comment by proux01** [comment]
Fixed upstream by https://github.com/coq/coq/pull/18527
